name: docker-compose 

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - run: docker build -t ghcr.io/smthelse1/node-server-alpine:1.0 node-app
      - run: docker push ghcr.io/smthelse1/node-server-alpine:1.0
      - run: docker build -t ghcr.io/smthelse1/python-server-alpine:1.0 python-app
      - run: docker push ghcr.io/smthelse1/python-server-alpine:1.0
      - name: telegram_success 
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: HELLO_MIR
      - name: telegram_failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: FAILURE
      
